# Generated by Django 6.0.5 on 2026-05-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_referralprofile_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
