# Generated by Django 6.0.5 on 2026-05-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_answer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_question',
            field=models.TextField(blank=True),
        ),
    ]
