# Generated by Django 6.0.5 on 2026-05-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_notes_lesson_quiz_answer_lesson_quiz_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assignment_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='assignment_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
