# Generated by Django 6.0.5 on 2026-05-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_free_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
