# Generated by Django 6.0.5 on 2026-05-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_enrollment_is_free_access_enrollment_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
