# Generated by Django 6.0.5 on 2026-05-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
