# Generated by Django 6.0.5 on 2026-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_enrollment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
