# Generated by Django 6.0.5 on 2026-05-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
