# Generated by Django 6.0.5 on 2026-05-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_quizquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], max_length=200),
        ),
    ]
