# Generated by Django 6.0.5 on 2026-05-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_quizquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
